backend:
  name: github
  repo: Maufive/portfolio-2.0

media_folder: static/work/images
public_folder: /images

collections:
  - name: work
    label: Work
    folder: 'static/work'
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: tools, label: Tools, widget: list }
      - { name: demo, label: Demo-link, widget: string }
      - { name: github, label: Github-link, widget: string }
      - { name: date, label: Date, widget: date }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Body, widget: markdown }
