backend:
  name: github
  repo: Maufive/portfolio-2.0

media_folder: static/img
public_folder: /img

collections:
  - name: work
    label: Work
    folder: 'src/work'
    create: true
    slug: '{{name}}'
    fields:
      - { name: title, label: Title }
      - { name: tool, label: Tools, widget: list }
      - { name: date, label: Date, widget: date }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Body, widget: markdown }
